### ISSUE TITLE
Release redirect ultimately returns a 404

### ISSUE THREAD

**Issue by eficker** [aerissecure/lps#1]
I tried to grab the latest release via wget, however it returned a 404. :/
![selection_053](https://cloud.githubusercontent.com/assets/5100114/11389259/cdaa64c6-92fb-11e5-8286-d2219ff333af.png)

**Comment by freb** [comment]
I'm not sure how uploading a file to Github goes wrong, but thanks for confirming the issue. I tried to download it immediately after uploading and had the same issue (from Chrome). Let me try a new release

**Comment by freb** [comment]
I renamed the file when uploading last time so maybe that had something to do with it. Just updated the release and uploaded an already renamed binary. Seems to be working for me.
